### ISSUE TITLE
Manny::mask method eating characteres

### ISSUE THREAD

**Issue by dany-eudes** [hallindavid/manny#13]
I would like to use this package with Laravel 8/Livewire. I think it will be very useful for my little project.
But I see him eating characters while applying the mask.
I press the keys one by one a little slower to see the mask being applied.

But unfortunately this side effect is taking place.
The mask is being applied to a Livewire component.

Versions:
Php 7.4.19

"laravel/framework": "^8.54",
"laravel/ui": "^3.0",
"livewire/livewire": "^2.0",
"hallindavid/manny": "^1.01",

I'm typing 12345678900.
And the mask is 111.111.111-11
So, the result must be 123-456-789-00

Thank you in advance for any help!

![lFfn1H85RQ](https://user-images.githubusercontent.com/82278/143339561-b862c5e9-cf36-43ff-a705-d3aca9d82e97.gif)

**Comment by hallindavid** [comment]
Hi there - can you see about throwing a debounce on there?  like 

`wire:model.200ms="attribute"`.

The problem you're experiencing is going to be occur because the data is being sent on every keystroke to your backend, and in the time it takes for your backend to reply, you've already input another character.  

I do this kind of thing with Livewire quite a bit, but you really want the user to enter the data in, and then a second later it formats it kind of thing.  If you want truly on-entry keystroke masking though, you'll need to write it in Javascript.
